name: coveralls
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: npm install, make test-coverage
      run: |
        npm install
        npm run coverage
    - name: coveralls
      uses: coverallsapp/github-action@v2.0.0
        with:
          github-token: ${{ github.token }}
